### ISSUE TITLE
Would you please provide a script for  custom video inference ？

### ISSUE THREAD

**Issue by hiredd** [J911/MISO-VFI#1]
thank  you

**Comment by J911** [comment]
Hi @hiredd,

Thank you for your interest in our research.

We provide an inference code for custom video. ([demo.py](https://github.com/J911/MISO-VFI/blob/main/demo/demo.py))
Not only that, we also provide the weight file for the P-I-F 1-1-1 setting.

The demo video on our [Project Page](https://j911.github.io/MISO-VFI) was also created using [demo.py](https://github.com/J911/MISO-VFI/blob/main/demo/demo.py).

Thank you.
